"""AspectCritic metric - Modern collections implementation."""

import typing as t
from collections import Counter

from ragas.metrics.collections.base import BaseMetric
from ragas.metrics.result import MetricResult

from .util import (
    BASE_INSTRUCTION,
    AspectCriticInput,
    AspectCriticOutput,
    AspectCriticPrompt,
)

if t.TYPE_CHECKING:
    from ragas.llms.base import InstructorBaseRagasLLM


class AspectCritic(BaseMetric):
    """
    Judge a submission against a criterion you define, in binary terms.

    You supply the criterion as free text; the LLM answers yes (1) or no (0).
    This is the most open-ended metric in ragas -- anything you can phrase as a
    yes/no question about a response can be scored with it.

    Usage:
        >>> from openai import AsyncOpenAI
        >>> from ragas.llms import llm_factory
        >>> from ragas.metrics.collections import AspectCritic
        >>>
        >>> llm = llm_factory("gpt-4o-mini", client=AsyncOpenAI())
        >>>
        >>> metric = AspectCritic(
        ...     llm=llm,
        ...     name="maliciousness",
        ...     definition="Is the submission intended to harm, deceive, or exploit users?",
        ... )
        >>> result = await metric.ascore(
        ...     user_input="How do I bake bread?",
        ...     response="Mix flour, water, salt and yeast, then bake at 220C.",
        ... )
        >>> print(result.value)  # 0.0

    Multi-turn conversations are scored by passing the rendered exchange as
    ``user_input``; ``evaluate()`` does that rendering for you.

    Attributes:
        llm: Modern instructor-based LLM for evaluation
        definition: The criterion to judge against
        strictness: How many independent judgements to take a majority vote over
        name: The metric name
        allowed_values: Score range (0.0 to 1.0)
    """

    llm: "InstructorBaseRagasLLM"

    def __init__(
        self,
        llm: "InstructorBaseRagasLLM",
        definition: str,
        name: str = "aspect_critic",
        strictness: int = 1,
        **kwargs,
    ):
        """
        Args:
            llm: Modern instructor-based LLM
            definition: The criterion to judge against
            name: The metric name
            strictness: Number of independent judgements to majority-vote over.
                Forced odd to avoid ties. Note this differs from the legacy
                ``AspectCritic``, where the parameter was accepted but never
                took more than one sample, so the vote was a no-op.
        """
        self.llm = llm
        self._definition = definition
        # Even counts can tie; the legacy implementation rounded up the same way.
        self.strictness = strictness if strictness % 2 != 0 else strictness + 1

        self.prompt = AspectCriticPrompt()
        self._apply_definition()

        super().__init__(name=name, allowed_values=(0.0, 1.0), **kwargs)

    def _apply_definition(self) -> None:
        self.prompt.instruction = (
            f"{BASE_INSTRUCTION}\nCriteria Definition: {self._definition}"
        )

    @property
    def definition(self) -> str:
        return self._definition

    @definition.setter
    def definition(self, value: str) -> None:
        self._definition = value
        self._apply_definition()

    async def ascore(
        self,
        user_input: t.Optional[str] = None,
        response: t.Optional[str] = None,
        retrieved_contexts: t.Optional[t.List[str]] = None,
        reference_contexts: t.Optional[t.List[str]] = None,
        reference: t.Optional[str] = None,
    ) -> MetricResult:
        """
        Judge the submission against the configured criterion.

        Args:
            user_input: The question, or a rendered multi-turn conversation
            response: The response generated by the system
            retrieved_contexts: Contexts retrieved for generating the response
            reference_contexts: Reference contexts for evaluation
            reference: The reference/ground truth answer

        Returns:
            MetricResult with a binary verdict (0.0 or 1.0) and the reason given
            for it. With ``strictness`` above 1, the reason comes from the first
            judgement in the winning majority.
        """
        prompt_input = AspectCriticInput(
            user_input=user_input,
            response=response,
            retrieved_contexts=retrieved_contexts,
            reference_contexts=reference_contexts,
            reference=reference,
        )
        prompt_str = self.prompt.to_string(prompt_input)

        judgements: t.List[AspectCriticOutput] = []
        for _ in range(self.strictness):
            judgements.append(await self.llm.agenerate(prompt_str, AspectCriticOutput))

        verdict = Counter(j.verdict for j in judgements).most_common(1)[0][0]
        reason = next(j.reason for j in judgements if j.verdict == verdict)
        return MetricResult(value=float(verdict), reason=reason)
