"""SimpleCriteriaScore metric - Modern collections implementation."""

import typing as t
from collections import Counter

from ragas.metrics.collections.base import BaseMetric
from ragas.metrics.result import MetricResult

from .util import (
    BASE_INSTRUCTION,
    SimpleCriteriaInput,
    SimpleCriteriaOutput,
    SimpleCriteriaPrompt,
)

if t.TYPE_CHECKING:
    from ragas.llms.base import InstructorBaseRagasLLM


class SimpleCriteriaScore(BaseMetric):
    """
    Score a submission against a criterion you define, numerically.

    The sibling of :class:`~ragas.metrics.collections.AspectCritic`: same
    free-text criterion, but the LLM returns a score rather than a yes/no
    verdict. State the range you want inside the definition -- the metric does
    not impose one.

    Usage:
        >>> from openai import AsyncOpenAI
        >>> from ragas.llms import llm_factory
        >>> from ragas.metrics.collections import SimpleCriteriaScore
        >>>
        >>> llm = llm_factory("gpt-4o-mini", client=AsyncOpenAI())
        >>>
        >>> metric = SimpleCriteriaScore(
        ...     llm=llm,
        ...     name="course_grained_score",
        ...     definition="Score 0 to 5 by similarity to the reference.",
        ...     allowed_values=(0.0, 5.0),
        ... )
        >>> result = await metric.ascore(
        ...     user_input="Where is the Eiffel Tower?",
        ...     response="The Eiffel Tower is in Paris.",
        ...     reference="The Eiffel Tower is located in Paris.",
        ... )
        >>> print(result.value)  # 5.0

    Attributes:
        llm: Modern instructor-based LLM for evaluation
        definition: The criterion to score against
        strictness: How many independent scores to take a majority vote over
        name: The metric name
        allowed_values: Score range; widen it to match your definition
    """

    llm: "InstructorBaseRagasLLM"

    def __init__(
        self,
        llm: "InstructorBaseRagasLLM",
        definition: str,
        name: str = "simple_criteria_score",
        strictness: int = 1,
        allowed_values: t.Tuple[float, float] = (0.0, 5.0),
        **kwargs,
    ):
        """
        Args:
            llm: Modern instructor-based LLM
            definition: The criterion to score against
            name: The metric name
            strictness: Number of independent scores to majority-vote over.
                Forced odd to avoid ties. Note this differs from the legacy
                ``SimpleCriteriaScore``, where the parameter was accepted but
                never took more than one sample, so the vote was a no-op.
            allowed_values: The score range your definition asks for. Defaults
                to 0-5; the legacy metric imposed no range at all.
        """
        self.llm = llm
        self._definition = definition
        self.strictness = strictness if strictness % 2 != 0 else strictness + 1

        self.prompt = SimpleCriteriaPrompt()
        self._apply_definition()

        super().__init__(name=name, allowed_values=allowed_values, **kwargs)

    def _apply_definition(self) -> None:
        self.prompt.instruction = (
            f"{BASE_INSTRUCTION}\nCriteria Definition: {self._definition}"
        )

    @property
    def definition(self) -> str:
        return self._definition

    @definition.setter
    def definition(self, value: str) -> None:
        self._definition = value
        self._apply_definition()

    async def ascore(
        self,
        user_input: t.Optional[str] = None,
        response: t.Optional[str] = None,
        retrieved_contexts: t.Optional[t.List[str]] = None,
        reference_contexts: t.Optional[t.List[str]] = None,
        reference: t.Optional[str] = None,
    ) -> MetricResult:
        """
        Score the submission against the configured criterion.

        Args:
            user_input: The question, or a rendered multi-turn conversation
            response: The response generated by the system
            retrieved_contexts: Contexts retrieved for generating the response
            reference_contexts: Reference contexts for evaluation
            reference: The reference/ground truth answer

        Returns:
            MetricResult with the score and the reason given for it.
        """
        prompt_input = SimpleCriteriaInput(
            user_input=user_input,
            response=response,
            retrieved_contexts=retrieved_contexts,
            reference_contexts=reference_contexts,
            reference=reference,
        )
        prompt_str = self.prompt.to_string(prompt_input)

        judgements: t.List[SimpleCriteriaOutput] = []
        for _ in range(self.strictness):
            judgements.append(
                await self.llm.agenerate(prompt_str, SimpleCriteriaOutput)
            )

        score = Counter(j.score for j in judgements).most_common(1)[0][0]
        reason = next(j.reason for j in judgements if j.score == score)
        return MetricResult(value=float(score), reason=reason)
