#!/usr/bin/env python
"""Build the docs and fail on NEW mkdocs warnings.

Why not just ``mkdocs build --strict``? Because the tree currently emits 75
warnings -- broken relative links, stale ``nav`` anchors and griffe docstring
mismatches -- all of which predate this script. ``--strict`` would turn every one
of them into an error and the job would be red on arrival.

So this is a ratchet instead: the existing warnings are recorded in a baseline
file, and the build fails only on warnings that are *not* in it. Fix a warning
and the script tells you to shrink the baseline. The baseline may only shrink.

That still catches the thing a plain (non-strict) build misses: mkdocs reports a
deleted page that is still referenced in ``nav``, or a link to a file that no
longer exists, as a WARNING -- not an error -- so a non-strict build happily
passes while the site quietly breaks.

Usage:
    python scripts/check_docs.py                    # build + check (CI)
    python scripts/check_docs.py --update-baseline  # re-record after fixing some
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
BASELINE = REPO_ROOT / "docs" / ".mkdocs_warnings_baseline.txt"

WARNING_RE = re.compile(r"^WARNING\s*-\s*(?P<body>.*)$")


def normalise(body: str) -> str:
    """Strip anything build-machine specific so the baseline is portable."""
    body = body.replace(str(REPO_ROOT) + "/", "")
    return " ".join(body.split())


def run_build() -> tuple[int, list[str]]:
    """Run ``mkdocs build``; return (exit code, sorted unique warnings)."""
    proc = subprocess.run(
        ["uv", "run", "--group", "docs", "mkdocs", "build"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        # MKDOCS_CI=false disables the social/git-committers plugins, which need
        # image toolchains and a GitHub token respectively.
        env={**__import__("os").environ, "MKDOCS_CI": "false"},
    )
    output = proc.stdout + proc.stderr
    warnings = set()
    for line in output.splitlines():
        m = WARNING_RE.match(line.strip())
        if m:
            warnings.add(normalise(m.group("body")))
    if proc.returncode != 0:
        print(output)
    return proc.returncode, sorted(warnings)


def read_baseline() -> list[str]:
    if not BASELINE.exists():
        return []
    return [
        ln
        for ln in (l.strip() for l in BASELINE.read_text().splitlines())
        if ln and not ln.startswith("#")
    ]


def write_baseline(warnings: list[str]) -> None:
    header = [
        "# Known mkdocs build warnings. Generated by scripts/check_docs.py.",
        "#",
        "# CI fails on any warning NOT listed here, so this file may only shrink.",
        "# After fixing warnings, run: python scripts/check_docs.py --update-baseline",
        "",
    ]
    BASELINE.write_text("\n".join(header + warnings) + "\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--update-baseline",
        action="store_true",
        help="re-record the current warnings as the new baseline",
    )
    args = ap.parse_args()

    code, warnings = run_build()
    if code != 0:
        print("ERROR: mkdocs build failed outright (see output above).")
        return code

    if args.update_baseline:
        write_baseline(warnings)
        print(f"Baseline updated: {len(warnings)} warnings recorded in {BASELINE}.")
        return 0

    baseline = read_baseline()
    new = [w for w in warnings if w not in baseline]
    fixed = [w for w in baseline if w not in warnings]

    if fixed:
        print(f"{len(fixed)} baseline warning(s) no longer occur:")
        for w in fixed:
            print(f"  - {w}")
        print(
            "\nNice. Shrink the baseline in this PR:\n"
            "    python scripts/check_docs.py --update-baseline\n"
        )

    if new:
        print(f"ERROR: {len(new)} NEW docs warning(s) introduced by this change:\n")
        for w in new:
            print(f"  + {w}")
        print(
            "\nFix them, or -- if the warning is genuinely acceptable -- record it with:\n"
            "    python scripts/check_docs.py --update-baseline\n"
        )
        return 1

    if fixed:
        # Fixing warnings without shrinking the baseline is how a ratchet rots.
        return 1

    print(f"Docs built cleanly. {len(warnings)} known warning(s), none new.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
